Bugfix yahoo-finance2
TypeError: YahooFinance is not a constructor

    at Object.<anonymous> (/app/stockService.js:2:22)

    at Module._compile (node:internal/modules/cjs/loader:1781:14)

    at Object..js (node:internal/modules/cjs/loader:1913:10)

    at Module.load (node:internal/modules/cjs/loader:1505:32)

    at Function._load (node:internal/modules/cjs/loader:1309:12)

    at wrapModuleLoad (node:internal/modules/cjs/loader:254:19)

    at Module.require (node:internal/modules/cjs/loader:1527:12)

    at require (node:internal/modules/helpers:147:16)

    at Object.<anonymous> (/app/server.js:4:38)

    at Module._compile (node:internal/modules/cjs/loader:1781:14)

Node.js v22.23.2